// scripts/build.mjs - emit runtime JS artifact for the OpenClaw plugin entry
// Uses Node>=24 strip-types to transpile src/index.ts -> dist/index.js
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname } from "node:path";
const here = dirname(fileURLToPath(import.meta.url));
const root = here + "/..";
mkdirSync(root + "/dist", { recursive: true });

// We output a JS entry that re-exports the runtime modules and registers tools.
// index.ts itself type-strips under node --experimental-strip-types, so we emit
// a distilled .js entry that imports runtime .mjs modules (no openclaw dependency at build).
const js = `
// dist/index.js - generated by scripts/build.mjs (v2 plugin runtime entry)
import { execTool } from "../src/runtime/exec.mjs";
import { runCua } from "../src/runtime/cua.mjs";
import { describeVisual } from "../src/runtime/visual.mjs";
import { spawnDSHWorker } from "../src/runtime/dsh-worker.mjs";
import { createWatcher } from "../src/services/watcher.mjs";
import { createScheduler } from "../src/services/scheduler.mjs";

export function createPlugin(config = {}) {
  const tools = {
    "odsh.exec": (p) => execTool(p),
    "odsh.cua": (p) => runCua(p),
    "odsh.visual": (p) => describeVisual(p),
    "odsh.serve": (p) => spawnDSHWorker(p),
  };
  const watcher = (config.watch && config.watch.enabled && Array.isArray(config.watch.paths)) ? createWatcher({ paths: config.watch.paths }) : null;
  const scheduler = createScheduler((config.schedule || []));
  return {
    tools,
    async stop() { if (watcher) watcher.stop(); scheduler.stop(); },
  };
}

export default { createPlugin };
`;
writeFileSync(root + "/dist/index.js", js);
execFileSync(process.execPath, ["--check", root + "/dist/index.js"]);
console.log("dist/index.js written + syntax OK");
